# Generated by Django 5.0.7 on 2024-07-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_compra_usuario_libro_compra_compra_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.IntegerField(unique=True),
        ),
    ]
